import { Flex, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import Header from "./components/header/Header";
import Player from "./components/player/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={`${inter.className} h-screen`}>
        <Theme appearance="light">
          <Flex width={"100%"} className="h-screen">
            <Navbar />
            <div className="w-full">
              <Header />
              <main className="p-2 bg-stone-100 h-content-height">
                {children}
              </main>
              
            </div>
            <Player/>
          </Flex>
          </Theme>
        </body>
    </html>
  );
}
